<?php
$this->headTitle('Registrarse');

$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Dirección de correo electrónico',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Contraseña',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row justify-content-center">
    <div class="col-md-4">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Por favor, registrese</h2>
            <?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Nombre de usuario y / o contraseña incorrectos. 
                <a href="<?= $this->url('reset-password') ?>">¿Se te olvidó tu contraseña?</a>
            </div>
            <?php endif; ?>
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> Recuérdame
                </label>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-lg btn-danger btn-block" type="submit">Registrarse</button>
        </form>
    </div>
</div>