<?php
$this->headTitle('Cambia la contraseña');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Página de inicio'=>$this->url('home'),
            'Administrar usuarios'=>$this->url('users'),
            'Cambia la contraseña'=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
            ]);

$form->get('old_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Ingrese la contraseña anterior'
    ]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Ingrese nueva contraseña'
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Re-ingrese nueva contraseña'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-danger']);

$form->prepare();
?>

<h1>Cambiar contraseña para <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <?= $this->formElement($form->get('old_password')); ?>
            <?= $this->formElementErrors($form->get('old_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   


