<?php
$this->headTitle('Restablecer la contraseña');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Dirección de correo electrónico'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-danger'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Restablecer la contraseña</h2>

        <p>Ingrese su dirección de correo electrónico a continuación para restablecer su contraseña</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint">Ingrese las letras de arriba como las ve.</p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
