<?php
$this->headTitle('Establecer nueva contraseña');

$form->get('new_password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Escriba nueva contraseña'
    ));
$form->get('confirm_new_password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Confirmar nueva contraseña'
    ));
$form->get('submit')->setAttributes(array(
    'class'=>'btn btn-danger'
    ));
$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Establecer nueva contraseña</h2>

        <p>Ingrese su nueva contraseña en el siguiente formulario</p>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                              
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>   
        </div>    
            
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
