<?php
$this->headTitle('Ver usuario');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Página de inicio'=>$this->url('home'),
            'Administrar usuarios'=>$this->url('users'),
            'Ver usuario '=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>Ver usuario <?= $this->escapeHtml($user->getEmail()) ?></h1>

<p>
    <a class="btn btn-danger" href="<?= $this->url('users', 
            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Editar
    </a>
    <a class="btn btn-danger" href="<?= $this->url('users',
            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-asterisk"></span> Cambia la contraseña
    </a>    
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>Correo electrónico:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Nombre completo:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Ffecha de creacion:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th>Roles:</th>
                <td><?= $this->escapeHtml($user->getRolesAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>