<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('MyGlobal')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/myglobal-logo.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/myglobal-logo.png') ?>" alt="MyGlobal">MyGlobal
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?php if($this->identity()):?>
                    <ul class="nav navbar-nav">                        
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('cliente') ?>">Inicio del portal</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('cliente',['action'=>'nuevo']) ?>">Alta cliente</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('cliente',['action'=>'todos']) ?>">Area agente</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('cliente',['action'=>'contratos']) ?>">Contratos</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('cliente',['action'=>'contacto']) ?>">Contacto</a>
                        </li> 
                    </ul>
                    <?php endif;?>
                    <ul class="nav navbar-nav ml-auto">                        
                        <?php if(!$this->identity()):?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('login') ?>">Iniciar sesión</a>
                        </li>
                        <?php else:?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('roles') ?>">Regras</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('permissions') ?>">Permisos</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('users') ?>">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('logout') ?>">Cerrar sesión</a>
                        </li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->pageBreadcrumbs()->render(); ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> <a href="http://myglobalux.com/">MyGlobal</a> por <a href="https://www.linkedin.com/in/thiago-souza-dias/" target="_blank">Thiago Dias</a>.</p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
