<?php
$this->headTitle('Ver rol');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Página de inicio'=>$this->url('home'),
            'Administrar roles'=>$this->url('roles'),
            'Ver rol ' . $role->getName() => $this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
            ]);
?>


<h1>Ver rol <?= $this->escapeHtml($role->getName()) ?></h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-danger" href="<?= $this->url('roles', 
                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Editar rol
</a>
</p>
    
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($role->getId()) ?></th>
            </tr>
            <tr>
                <th>Nombre:</th>
                <td><?= $this->escapeHtml($role->getName()) ?></th>
            </tr>
            <tr>
                <th>Descripción:</th>
                <td><?= $this->escapeHtml($role->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Fecha de creacion:</th>
                <td><?= $this->escapeHtml($role->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>

<h2>Permisos</h2>

<p>
<a class="btn btn-danger" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
  <span class="glyphicon glyphicon-check"></span> Editar permisos
</a>
</p>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
            </tr>
            <?php foreach($allPermissions as $permission): ?>
            <tr>
                <td>
                    <input type="checkbox" disabled <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
                    <?= $this->escapeHtml($permission->getName()) ?>
                    <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                    <em>(inherited)</em>
                    <?php endif; ?>
                </td>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
