<?php
$this->headTitle('Editar permiso');

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
            'Página de inicio'=>$this->url('home'),
            'Administrar permisos'=>$this->url('permissions'),
            'Editar permiso'=>$this->url('permissions', ['action'=>'edit', 'id'=>$permission->getId()])
            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Ingrese su nombre'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Ingrese descripción'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-danger'])
        ->setValue('Guardar');

$form->prepare();
?>

<h1>Editar permiso</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

