<?php
$this->headTitle('Ver permiso');

$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
            'Página de inicio'=>$this->url('home'),
            'Administrar permisos'=>$this->url('permissions'),
            'Ver permiso'=>$this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()])
            ]);
?>


<h1>Ver permiso</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($permission->getId()) ?></th>
            </tr>
            <tr>
                <th>Nombre:</th>
                <td><?= $this->escapeHtml($permission->getName()) ?></th>
            </tr>
            <tr>
                <th>Descripción:</th>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Fecha de creacion:</th>
                <td><?= $this->escapeHtml($permission->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>