<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <img class="img-fluid mb-4" src="<?= $this->basePath('img/logo_completa.png') ?>" alt="MyGlobal">

    <h1>Bienvenido al portal MyGlobal para agentes comerciales.</h1>    
    
    <p>
        Si es uno de nuestros agentes, tiene preguntas sobre el uso del sistema o no tiene una cuenta, envíenos un correo electrónico.
    </p>

    <hr class="my-4">
    
    <a class="btn btn-danger btn-lg" href="mailto:rrhh@myglobalux.com" target="_blank">Enviar un correo electrónico &raquo;</a>
</div>